name: xml lint

on:
  push:
    branches:
      - master
    paths:
      - '*.xml'
      - 'Desktops/*/*.xml'
      - '.github/workflows/xmllint.yml'

  pull_request:
    branches:
      - master
    paths:
      - '*.xml'
      - 'Desktops/*/*.xml'
      - '.github/workflows/xmllint.yml'

  workflow_dispatch:

jobs:
  lint:
    name: Run xml linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install libxml2-utils 

      - name: Run xmllint
        run: |
          xmllint --noout *.xml Desktops/*/*.xml
