name: xml lint check

on:
  push:
    branches:
      - master
    paths:
      - '*.xml'
      - 'Desktops/*/*.xml'

  pull_request:
    branches:
      - master
    paths:
      - '*.xml'
      - 'Desktops/*/*.xml'

jobs:
  xmllint:
    name: Run xml lint check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install libxml2-utils 

      - name: Run xmllint
        run: |
          xmllint --noout *.xml Desktops/*/*.xml
